app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, lm
from flask.ext.login import UserMixin

# Classe Usuari
class User(UserMixin, db.Model):
    # Taula SQL
    __tablename__ = 'users'
    #id unica de cada element
    id = db.Column(db.Integer, primary_key=True)
    #Nom de usuari
    username = db.Column(db.String(16), index=True, unique=True)
    #Contrasenya (encriptada)
    password_hash = db.Column(db.String(64))

    #Creem la contrasenya encriptada a partir del text pla rebut
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    #Comprovem la contrasenya amb el hash
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    #Metode per a registrar nous usuaris.
    @staticmethod
    def register(username, password):
        user = User(username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

    def __repr__(self):
        return '<User {0}'.format(self.username)

@lm.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length


class LoginForm(Form):
    username = StringField('Username', validators=[Required(), Length(1, 16)])
    password = PasswordField('Password', validators=[Required()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Submit')

app/__init__.py
import os
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view = 'main.login'


def create_app(config_name):
    """Crear una instancia de l'aplicacio"""
    app = Flask(__name__)

    #Importar configuracio en funcio del tipus de aplicacio (dev...)
    cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
    app.config.from_pyfile(cfg)

    #Inicialitzar extensions
    bootstrap.init_app(app)
    db.init_app(app)
    lm.init_app(app)

    #Importar blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #configure production logging of errors
    if not app.config['DEBUG'] and not app.config['TESTING']:
        import logging
        from logging.handlers import SMTPHandler
        mail_handler = SMTPHandler('127.0.0.1', 'error@example.com',
                                   app.config['ADMINS'], 'Application Error')
        mail_handler.setLevel(logging.ERROR)
        app.logger.addHandler(mail_handler)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
from flask import render_template, redirect, url_for, request
from flask.ext.login import login_required, login_user, logout_user
from ..models import User
from . import main
from .forms import LoginForm


#Login tipic
@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.verify_password(form.password.data):
            return redirect(url_for('main.login', **request.args))
        login_user(user, form.remember_me.data)
        return redirect(request.args.get('next' or url_for('main.index')))
    return render_template('login.html', form=form)

#Logout tipic
@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/protected')
@login_required
def protected():
    return render_template('protected.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login Example{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                Login Example
            </a>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.protected') }}">Protected</a></li>
            </ul>>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if current_user.is_authenticated() %}
                        <a href="{{ url_for('main.logout') }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('main.login') }}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Home page</h1>
    <p>This page can be viewed by all users.</p>
    <p>You are {% if not current_user.is_authenticated() %}not {% endif %}logged in.</p>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Login</h1>
    <div class="row">
        <div class="col-md-3">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/protected.html
{% extends "base.html" %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Protected page</h1>
    <p>This page can only be viewed by logged in users.</p>
    <p>You are logged in as <b>{{ current_user.username }}</b>.</p>
{% endblock %}